apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:iHhLYXWItY+PR8P2TiyIu5+yy2/t24FSFPjDyEmqbwFcQ8ucj65EkDXRv1eHfS0F1yGk4h8=,iv:7PlGXmLkSXXnguT3C/vXfRik1QIdSp53G2UvjKL0hNE=,tag:UpmnlXA7F65Y8pE64oX9NQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFpOVWQxQU1t
        S1Z3UzdLM0k1cWVWWG5PeDcwNlFLU1AzWU5rNWxpOE4rNDBNdXhsYk9BWWQ0cEdM
        ZTRFV1RNN1NvaUZpeHRSSjZESjgxRkNMLzFndWtjVFdpMmtMbmRYWEVnalJ4QS9z
        cTlxLzNWOHJVUHF0dWEyaEs3SnNZWHFxT0lzTnY2anpIMDZkZ3piaDdHYWJIMjJP
        SHZUYnA2OUovK0ZqSVlLeWtMYldZLy9oMTM5TTQ4R3RsWmttNndiaFc3RVZDR0pB
        WTRFUnhEL2dKZDRESFhQMVdOQ0JVbktSQ1BLOFowSU1LWG5xTjVuRGhiWW1zaHlH
        RVpoM0VPRzhnaDBMcE5JTTJwRUM5TEdXYXA5ZjIweEFQTjVuZ0VjVDNNQTN2S3Ft
        OHUvLzFFV3lyK2dIQ3VqNDNlcnVpZGtQQUczMm5oaGJqTVloSDVlUUVJNHdlYVZX
        alFITlJTN3pLK3hySEFxM0NhYU1pK1hwTEd0L1RXejFuVk93NmFwcXNYUm1ibkZv
        Q0xVSmcxa2pxTnQrV0xQVnlEZDVtcVpnWkJxYjlCenpYaUJhc2FZZmJGTjNFOXV6
        b1dtby9RWCtCQm9oc3Q3WEg2dWx3V2RxZVl1ZjJoMk9hVncyNmxINU9kYkh0U085
        aVlmMVlUYWU5N1B1akNlU0F4M1NSOU9weDd2R1ltS0lUbUxHRnBRTmRZM1YrYU9T
        Q0lUZnVQYXR0UFBTVnBadXgzeVlPMVJDOFkxeDZDTWE4SE5WdHNoUjlrWEpnNXJY
        RUM2ZzM0V2E2cVl3VncvUStEWXR6SEduc2prdlE5UHNWR25WK1NDeTBNRDJxN0ZX
        d0FvZHpKWERhaDV2KzM2U1dvSGVIWndWdHlZeWVlc3VMUjZ2azlPdk9hM2tueTZj
        aTAvY0RyNTRURC84aW5ndUpqUTByalBJSnFmc0MyMzdPUEcwWHJ2azJiMFRxQlNi
        VXNmQTFZM0Y1VjBKUHd3WVlKSXpCY0NmTjkreGFUcVFUOEprQWgwTkxsSGRDYm01
        MzJlZE15bWh6dTJHeGl5TldQUHFINDdqTmk1cWtBcmtxdUdOenFGbnFPNFRZaFRs
        WnNVaGtkVnc3aTZDQ1BZMGxGY0twQlpDVWFieVhKNmk0cm1MSVJPTmNkZUJDekRv
        d3dXQ0RGY0h6VFVMR3lRenA5RU5tcUlKWFpoVDdOQkVZaDN6c2FtMklFa2pUYnVp
        YnFqL0syV2xHZThzTHhiZkNieFZYa3lXWU9PRGdsc3A0bVRkL0pibG1yVlNCVU02
        VWk3QmloUlZOVWd0akJ0d3pzM1RDSXovTUtsWjhKT0lqcnZmdGtJaGZFWms0NXBp
        bjBOS055NldWUnVkb1VQbWt1RWJXcGF2RXk0c3FsTDBhWVdhcy8yNXIxSG5nRUlz
        WDFkNnVkbTRQYXd6bG9XZjVlMU9Kai9MeTlDZVl5SVA5R3JRZDlYeVBsVVJicVpz
        TmsyTVg0L0w4T2Q3a1EzYUh4ZzdkTGJMOEErQkc1aGREUmJhbGgzVVBzU0RiTktn
        bmJCN3hOSEluRGpxY3JsbzBVeS8wa092QXgwMHdubHRiZEVGTllMODVnSDJDNDZB
        by9jWVZEYVJPak52UXgybFNWQjNTZHZLVytOeFgwV0hScytybzVPMTNENmRwTkZQ
        UXQvTnl0WFpkTlAyV2FZNC9FdHRPUld1bjF5cHNhRFFWVXFRaFpFZ0c1dy8rZ0E3
        aWN0TmFRSUZUY09Yd2tFWW9nT2R3U3kxcnJVc0Fqb3VjbUthS3pJWkNPOUx0Mi9G
        UjZCSnlqWi9DVHVWaCtKejJDMFhudU9DZWFPbjB5RDVORWgvY2tueG9mMmwwWVlP
        aWlINEVFK1R4Ri9YVCtaV3pUMUFtcVFMcE8xMXpKbHJpNk5aaHE4cUhoOGh6TlNV
        N25ZZklWd29jcDhxejRGeHBETTJGSlFDSUhvei9RZVliNGZsOUxlekt3ZTFHUQov
        RTB1YnRrbVc1VmQzeTB3UmJYVlhlL0dHcWZVTVRjWCswZ2I5TTU3MHljCi0tLSBW
        WnFrVHd0aGM2NHdiSzJqUzhzL2xGOVgrRm9PNGd1ZkRxSHEyUnNaQkpNChHpIbJs
        3Bt97Pj7MmLiv2nC7CEaSYkggza/Z1Rm71d5Ed6YFOsjbGyHDMd6ijAP8HmpVoOE
        u6Ktmb8NLMtcWUM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1xjdsvzx6h4rawj5f4zdmeysndw95znvkrh4eweaaq7qsllqntsfjegm42w2vntuvtf5jsq6cw5t58ymf5w00wxerc36qswpxetjuyugr02fhnwed5wrnj5t4eamylyj4pn89tw37hzulpgq038pxltxg5nrs5mzf57z6s5sre79qs4y24yjsz3qr7pyanw9sp43squ8c3c6xxeqpu4j7vrpnpnvj5k4mv9vacw3qqsqgzxxtl9vy55lshcl3gm32s5t5y4ct0ldrg3y2wln4qrmj8xgtppark7tc836jtc822hfyvedptsxdezg2jkennrpfdgjfkdsunsypq4rjlcyxrwgp334jqg5m24th34ccguvrfzv4djjc4g7gt344sjx2k56nxnznpnpe0t9v6qp7cgj4juuu0x5nn9lg6dgjgfzr386jaxj5rx9ncg6qj4nuw9zy8zdnqpcf50y2qy63662yejarjk4njnurvlukyaxqsy22mkgsjujzl5s98rr026rsc36u7jtj3qu9fh99z5lvjmyqk9sffydfd5jt5gjx4y6l5z4vg6385ae0nkmmtnlh87tq8jezct828e3ce8ufvyu2wpuqrp4xzdacx4j09mx2g0f48yalrjd7zu0x6gmq88grnfm6wax8cl0evzrry9392uj9rgfmsxnf4swcddfgedjw299y7eh4v8932qa052jh7uc0hvpk5k0petmzqn77hjg8gaycxmr9uv690m5mver3x6c3y9gp326glheqemwhedrva2gwh2cls4y295l4z8x2p0ef9dqjx4yarjsrnv7cc5has9urnfxycqyd4u5q0wmqrr6rcl8d8srll92gfgxqlz6txac3vuqvx9jnh9mme5pt3dmu5axnnpxkwdcsgys8ksrgqg9n4ymjx96sq55kt9rl3vtt72dqzckkwpjrup4nxfvynh48rzz4fxm62ml0uy5a0em532v4vr9hzvw3jh9vhv3u7922d59r5tjyhhtje0fuxv6gd9fjd5cptycnyr8c4pxk65p42s2sl2gc60l43kyljqgsj8x602szvqruym0k5f3ds4pc8yj73z7g4m5ywllryefycjvl5kulrjppde6qq6uh45zppw0066jlw3esqa9q5q4t3txw9x4hk735hzzuxutc47w4hmexdrshkpfa3sqxpe9rn62mhcqe9r6zxfljkgvhvzpggrr3qlvusjrkz2cjmsfph6uy2v46dfzzv8mdcuscl4n5uc2nuzzhztqxjrd2q2hhk8rsmeeufw9epj8a3vfvfgxxue90j44jnwv9jx5q3rh06jrfj6u5rhct5ngvgqqarq0a5y34u297h9xfl64qymrvqc38rgxedqznlcyhr7j49a35ffyev48wzqygg86y54jqs9e9gxztckvwejurueg5952c2yc02epn3zsde7acyf34w4ltk3m0dj05j53xgfare44s0dc5z4cfc9jpuqapq348hgmcu406k6kdzp7jpx003xcmpgjee5ap55t5x4rr2as3q57zk4syx4mnk6z9vlhn2vwvhrqhsevserxxj45wwzp8c0qs60zjqxaxp4vf3pn8ch60c4pnhekwdkkv3ap4hrh3qp7sw54dcu464ajeky0vhntcppdqu5lykk33ykt3h5jc9ehrx7lnm969mx6m86cqzxcfr2u52zkgl0pztcq305ju6h0te3jw8frm238d4c2u3vy3ttq3j3frkz3hystugvsen0cur5qn59ty2fvx6nzjfagw8vjr5aqckttr0f0gxvp852gwys92qdrjqun52yk7uftcyldh5fryvzvz2t8z45k92qzn2smh50r2yylcf7l607xjep65407exs0yaa56hqn79v9ypam0ggsj67ce959we7yupahzk5nh57evdsy2sve7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T19:45:53Z"
  mac: ENC[AES256_GCM,data:JYK2ncGSgjcOTeMYhNNrVugjLqlyF/60SMQ1J4JevaE6VKboTgXT7pUjYNTTPMSdoM6k3ldZq3eexcHwuII0RX94zxnBSq7NRx/uBNAGSLxwQpXDRCtMHt/NZlhFTs1dHvMCNKqa3bV6EJVabtNbpMBsVp6ZxaOnZuJrQmZLmIo=,iv:wp2eoUFYq/NLpT3/psNE2Ch7BdY8N0xHvLuMjdoUuvQ=,tag:/+rS+vTBOXdohXG3p/c74Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
