apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:bGkRSkEF5UQVIjA+Qlyo0nu+xEE=,iv:2Mg4HeqMFoiH1qex+xCd1UVkG/bxC1rO7gNJ0ISJmxA=,tag:sFw5HtaQzlROeXlLQQqJ2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG9yTFdNc0or
        WFJFM3lsN2RZR3lHbXVwaU9VTFdwaExPVFJKbjJ2L0FhYzhkUDhBRjBKbVVHTkVW
        REM3MEtNWVVWakpXQUYyK2tKYU4zSFJHSzE1UGMvQjlQempqcTE2OFk0T1NqdkFp
        U3lvVXlYaDdTTUt4Y2FGTWJRUkd5UzBvZ0IrS1UvYXAvb2VNZ2J4NkptaVk5SXN4
        NnZWbldneXp4OHBGTm4yMVlkTlRDR2gyTnhOVFptR2t2L3FHQnNzb255a0dGZDVr
        WGduMHNkSCsvYTFjRmwxQkZwWCtXTkFVR3p6NUdpcWFENWdCeXZmNDFSdzRhRDEw
        ZnNQSERwVlBsaWFQTFJ4aXBMUFhTMFFWZlZ4WmNVa2J5UDVOb3F0VnAxZ214OHEr
        Uit0RmFPNk92Y0tzMlNIRS9pNW8vek03ZGRnK2g1Uk1SdjkyYlRwVFFscW16N3JV
        V2dFUDNKQmZQNzh1bDFJSURyQzhSN24weC9zeE9wTlovR2hobUk1aENEZ3FIV3BL
        Ryt1SGpCckc5Tm9CMms1UDV0TXhIRGRQSEJsWkVTNnJXZWN2V2lWTGRtVGpTSCtC
        N0V6NG9WQnMwRWUwSjZiMUJZbDZMa1VpcklTNWprUThUaWpCaU5tYngvanJSTjdQ
        OGgrSzhWbFlPWTJScmRBL0xqVk4vdndyZVBtaEhQbk9sMkQyMjBQZkJ3b2FQWHpQ
        eUtvYUNEdnpDL2VSaWd6ZVZaVkFPaDV1Ty9ENDZqNWhRbmczR0prdzlDS3NmdVNJ
        bXhUQWE0UnpNK2JlNXJqcTQrM0RsTHhkM2o2TGRyTk9XZjlWVEp3UEJzS2tKWFJo
        eGJuY3VuNlVzdVorOWVBWjVlczAvV1JydTd4ZFl3VnBPTHpGeGc1RHYzRjlqWDVV
        dmxueEwxMWpxTWNZMXc3N1FER1A3MVNFajB3a2UvbmFYNERwcHppejBRSk5NSkI2
        ZStlK1RyUE5MSUQ0TlJHelg4eWsxbi9iRDl0RTBZMCs3WGI2a2tYZ1N2YnpRQm9G
        My9HakFnUUlnK2xJT3pNd1BWZkhHQjFhZVNpZUN3eXdXNzFKTWkzdmZySkJGRGNI
        akExWkQwRmhPQldoUUJZLzlVbVMwVC9oR2VGcVZCZEc5ZmRJbzYwaCthTTFYN3pN
        eXpWaDZ2TXNScEdjajhlSWRHRnFEM01VL0pidnd2MUZlSjFFamhaamFBRDN5eUpx
        ZWtpempJS1NiSVEwRXdGRTVyMUl1QTJDdWxpMDV4amtIUENDdHROTVk5TUlUYVBB
        UEhXYWhEN2Z2a1pBYlp0T1BFYXQ5aWtBeGdUR21pK01kUExHenBxZWVqeU8yaEJB
        MFlvWVhYVVlyZVMrV0x0alY3UlBZQ1VNdWFrZ21PL2VNZTk1OENwRkF4OVVnVG1L
        K1A5WGttRnJVU1pCaHdqbHJNRmI2ZEdRQ3VybUpBR2F6SEx1ZzBIQ2xTL1ZQU3VS
        RTRiNXNqVmJMditENzR2azArWEJTRmtiak02VTNCZ2c4OUoyL3JwVVF1K1RFNDkx
        c2hTd2laUFhLWWdqZFgyc3BQM2NGakRiTWFGS0NXTXY2QktRdVU4djdsOThneUNV
        R3lsUzl5WlhiTnJpUnpYMkVLMU00NjVNbEZEUWliWUhIazlRaUJDdFJ3QXBjSnJE
        Q21CZHNjRTBNTHFvUkpNclRBL3FtcTBZcHhPQWMzeEpRMklFVUhOQ3F2ZzhWWWwx
        RTNmbURFaTc3SU16bXQwSmxPditzM3k1TW95ZHI3NnFrL1lObUdTVG1qdXVTZ2sv
        bEdsYVFFVHRQNlBnUWQvN3pSRWZ3TDZxT2ljaDhKN3hJTG93ZzRTSWo0WjJYUnZ1
        UmRtdTUwaEREcStvZ3NOMlVPampEOTFYTGpYd00rWjNscWpUY0pFM2l1WElqTVla
        eU85djhQOVpVY0d4bjYyWjI3SG1EVUQrVWthcGNBbStZNFRXWjJ5RmJOclJZUQpW
        NFN4Rlp2RFFiWk9NSGhwVWZqOXplTVdRQUMxbmY3VE5QbTVZRGRyKzE0Ci0tLSAr
        Z01Ld3Q4OUFLRkdKZWhWK0ZPdVpTa2hRaVNacElVZmNhT3VOekdlZHJjChdWGFhe
        Y+So/L0W9wEXONw2lcSv/lOnkYdIw7H5uw/fa+3mw3KNjqZh82MP3WNYlEL8xqDE
        FhoD36fGt7Otvx4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1xjdsvzx6h4rawj5f4zdmeysndw95znvkrh4eweaaq7qsllqntsfjegm42w2vntuvtf5jsq6cw5t58ymf5w00wxerc36qswpxetjuyugr02fhnwed5wrnj5t4eamylyj4pn89tw37hzulpgq038pxltxg5nrs5mzf57z6s5sre79qs4y24yjsz3qr7pyanw9sp43squ8c3c6xxeqpu4j7vrpnpnvj5k4mv9vacw3qqsqgzxxtl9vy55lshcl3gm32s5t5y4ct0ldrg3y2wln4qrmj8xgtppark7tc836jtc822hfyvedptsxdezg2jkennrpfdgjfkdsunsypq4rjlcyxrwgp334jqg5m24th34ccguvrfzv4djjc4g7gt344sjx2k56nxnznpnpe0t9v6qp7cgj4juuu0x5nn9lg6dgjgfzr386jaxj5rx9ncg6qj4nuw9zy8zdnqpcf50y2qy63662yejarjk4njnurvlukyaxqsy22mkgsjujzl5s98rr026rsc36u7jtj3qu9fh99z5lvjmyqk9sffydfd5jt5gjx4y6l5z4vg6385ae0nkmmtnlh87tq8jezct828e3ce8ufvyu2wpuqrp4xzdacx4j09mx2g0f48yalrjd7zu0x6gmq88grnfm6wax8cl0evzrry9392uj9rgfmsxnf4swcddfgedjw299y7eh4v8932qa052jh7uc0hvpk5k0petmzqn77hjg8gaycxmr9uv690m5mver3x6c3y9gp326glheqemwhedrva2gwh2cls4y295l4z8x2p0ef9dqjx4yarjsrnv7cc5has9urnfxycqyd4u5q0wmqrr6rcl8d8srll92gfgxqlz6txac3vuqvx9jnh9mme5pt3dmu5axnnpxkwdcsgys8ksrgqg9n4ymjx96sq55kt9rl3vtt72dqzckkwpjrup4nxfvynh48rzz4fxm62ml0uy5a0em532v4vr9hzvw3jh9vhv3u7922d59r5tjyhhtje0fuxv6gd9fjd5cptycnyr8c4pxk65p42s2sl2gc60l43kyljqgsj8x602szvqruym0k5f3ds4pc8yj73z7g4m5ywllryefycjvl5kulrjppde6qq6uh45zppw0066jlw3esqa9q5q4t3txw9x4hk735hzzuxutc47w4hmexdrshkpfa3sqxpe9rn62mhcqe9r6zxfljkgvhvzpggrr3qlvusjrkz2cjmsfph6uy2v46dfzzv8mdcuscl4n5uc2nuzzhztqxjrd2q2hhk8rsmeeufw9epj8a3vfvfgxxue90j44jnwv9jx5q3rh06jrfj6u5rhct5ngvgqqarq0a5y34u297h9xfl64qymrvqc38rgxedqznlcyhr7j49a35ffyev48wzqygg86y54jqs9e9gxztckvwejurueg5952c2yc02epn3zsde7acyf34w4ltk3m0dj05j53xgfare44s0dc5z4cfc9jpuqapq348hgmcu406k6kdzp7jpx003xcmpgjee5ap55t5x4rr2as3q57zk4syx4mnk6z9vlhn2vwvhrqhsevserxxj45wwzp8c0qs60zjqxaxp4vf3pn8ch60c4pnhekwdkkv3ap4hrh3qp7sw54dcu464ajeky0vhntcppdqu5lykk33ykt3h5jc9ehrx7lnm969mx6m86cqzxcfr2u52zkgl0pztcq305ju6h0te3jw8frm238d4c2u3vy3ttq3j3frkz3hystugvsen0cur5qn59ty2fvx6nzjfagw8vjr5aqckttr0f0gxvp852gwys92qdrjqun52yk7uftcyldh5fryvzvz2t8z45k92qzn2smh50r2yylcf7l607xjep65407exs0yaa56hqn79v9ypam0ggsj67ce959we7yupahzk5nh57evdsy2sve7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T19:45:53Z"
  mac: ENC[AES256_GCM,data:GgOMvHDoalsOBm7sSBjkeahqJZziD7W4G7RIkBKXlefpqVI/xG825djUjkO/OHvEH9bqd3iD0v63jdkko8GA9FCOOVNYoTaGHL/owtygHiYZILa+6xvvHQZkiOx0AwSa1+50ZOe4o5q3DcXLTVk0PVI08jchgr7153Aa+4LR8Jo=,iv:vq8V6dvX4FexHhUf+roNIRX7HBF4b6fZaYBiF9fc0H8=,tag:nUfJnglb2uL9Yvp/8rBzYw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
