apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:WBJftV8X1tGGKDCCIKcHxZ+/hF7FOR8yfq1/GeVWPdW7abxu/UsxRRE0QL3xh0LMzdhggcGe+Dld/w+0TEJNWjrkgO/jtsBFk0h7BJ5I7aNFAjOsLuyA8Ofs/zk355q+jYWwNwCNGXF62Zq9crrEw1nisA/zWUbZ80PXHsJFgVFw3xw6zsAdqhBqUcGNmFcINToEOv2X3HAr/Mp9i90yYqbfgwH/Svub+DnBRzYfmP7iTfxl,iv:P4yGQ06RpyDLu2yVYMmoW5jhdndZJz3Nr3mIzgTH+XU=,tag:ETwQ49Vy6ReXtPY19YH0Sw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFRkUXNzMk5O
        SXpmNGhNUHZCRFlsbCtQUFZONFoyZDZYVG9sOGx5R2RDblZpUEErVDd4dkdKTTF6
        dFMzTzR5VlgyTnRxQk95YmhJWmlCSnFYVGRlUkZOZGFOU0p1VkJNSE95TENuWVVm
        RWJkdWVEaTAwOEQ0YS9DQ3pSVklpTGh6cVlBNndZU0w0bjMrckpXRitoWlRqWXBI
        Z0lOeXhFUXdnSlBZcHEwaWkvU25JVFh4ODhLSFdKNUUyYjNFZnlwSmVnN2NUL1Vr
        N2hDcWR3ZTVaSnZPOUtzWS9SOTN4Y2RqTE1lN2d0enloM2FvRmxqSlhEUG45TElU
        b2dkOFhtTWZXWHRsTzE5Sm80Ui9uelFVQVVRdTVpMWk0aUxiYlh3azZ6bWppbjhw
        TTZoV3JhY2RqWkhMYmdFeEFYUnY3Ym9hUnBLM3Nnem9UVHFxMkV6b05KYS9GQ29m
        blNDWkFRWXBHTHk3c2NyZWxHMGNjTytXWHRsSzYreU9oTEdoVDJSWXhTNTMxWVVI
        bG1nUkIvQU9xVnI5d0doV0pZcURrVFRqQkhSbnhkMGtRN0kvRWt6WXFPRmpiWGtP
        RnkxbzA3ZCtVMm5hcnFpZnpEMWtNVnpNVjYwQ2MvM1d4QlkvMm94YzhWV2N0ZW9i
        cy9Kd0RJTjdEVkFtRUFWVmFWZldqSEhSVXQwaVpqKytOUjdmdTJWd1JjU1lFS0tm
        NUZVMmVvMEtKWVhXaUtDLzhId045MHY4NGd0UTJWTDlRcDBiWjB5N3pORmQ1MFhz
        MHpwVUJnOW1UanhnbmNhQWsvNVh6dlVwSGZRdDRiMXd3TnJEZzIySWNzMHA5am5X
        cC9EZk11dlhxd2pMNXVNOEhhSmxUNi9tMkdoVnpIc1BTenRNQi9jSm9DNENXVCtF
        RE1LR2JDbnpHUzlvME9PR2RqanVnbFZ6OWppbHVibFY3UEY3NnFMMFRuOGJOM3ZG
        N0dxTisvbHFsako2aWh1TDI3WEtTb0ZLNDBabTlVUUdOdzVkam9BanhnOE9KUEdL
        ZFFNUWlWNEs3MG9jOGJEV0FPK3kvVEt3VStvZHNFc3NnRWFJeEhWN3BHNGo0dSs4
        SXpWYm5kSHFVNlp1NGFVRGhLM2FSekhPSlVVSmFsenQ5a2xmdUwwL2kzV1Rjd1Nl
        NVBGY1BWb2ZGT0hKdEoyTXQ2WUVPbE1LOWZyZVFVeC9Kc3JXOXVtZVV4TDZIM0NE
        U013M2pDeDUrdC9jTVpJRnlpMVllbERna2ExS1pxam52L3J5ejErYkVQRitlak16
        RS82L21TL0h2K1o5TXp5YTNERGhPNlUvMnl5MDlEUTVmY29WenlTOHNqNmJ4OVZZ
        ZkhiTHFsT2I4OEFEQ3ovZWFrYnU1blVVZTV4YnlXTzJiMitiRXQ0RHVXWDhlWEZD
        ZlU1dklxQ0VrNmhqTjFyZk5FMGpLZ040dGRFN2NnOUhsUTh1SFVIc2phY3NVdkZM
        ZDI1ckJrL2VjcUJMRW9sODlwL3c2cDlTVGUwRUUxM2JaZkVxRHAxcWtyc1VvNEFi
        bG8vOTh6VXBjamhMTzBHd1ROL1F4YXhBSWxMMzZCbUZXL29QQnpTVUNjNEtxQmVq
        N1YycDR0eTlTa2toMW5BWmtCMnFMWVdRK2RvS0swdHA5UkdHdG5WU2RUVVdNRVJi
        SkhYY2FEcUVIZG8wU2ovdG1uTDRFa1NZanFSRWdVRmZNTFB1bldaaitoeTJrY0dM
        dnA4czhhWXNqdHNqcEtDRmFSVHRsUStiYTF5SHVScXZXaVlpZU1ZRnk1d1lQNDJp
        dXRBaXU5TCtwK0pmc1V0NnppeDk0eDZqUDl4OVpkYmFIK2kyWXkxYXpuTVo3NFhH
        RmNnc2Rab1RGeXY3c3BYbDFCdzdFbnhGSDNDS1VvbHBUL2FRTzRaV2N1Q1ZBVVhT
        cjB2WHhoSnZNSUUxUjBDejhwN1gwWElYN2tqZ0hFQlR1MXhkcHptQzB6WWZWQQpD
        VHRXeEFoc0VMZS93bmtvTG5UZmRwbXk5UXFrRnBPOTVTUi9jK3BNZHdvCi0tLSBV
        QVpnWlZNSVBwNnJJMElMbEkrdjFYdDRUcjNWZ0tqenNmZDBpRlJxRkYwCm/bHRNy
        ZPostQxAsel9Lntan9bAbABE2+0uSOaQCWuKDl+g4uX63T3jf/dztfc2sZH0JqE5
        tE/YAqJt3cuWBVE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1xjdsvzx6h4rawj5f4zdmeysndw95znvkrh4eweaaq7qsllqntsfjegm42w2vntuvtf5jsq6cw5t58ymf5w00wxerc36qswpxetjuyugr02fhnwed5wrnj5t4eamylyj4pn89tw37hzulpgq038pxltxg5nrs5mzf57z6s5sre79qs4y24yjsz3qr7pyanw9sp43squ8c3c6xxeqpu4j7vrpnpnvj5k4mv9vacw3qqsqgzxxtl9vy55lshcl3gm32s5t5y4ct0ldrg3y2wln4qrmj8xgtppark7tc836jtc822hfyvedptsxdezg2jkennrpfdgjfkdsunsypq4rjlcyxrwgp334jqg5m24th34ccguvrfzv4djjc4g7gt344sjx2k56nxnznpnpe0t9v6qp7cgj4juuu0x5nn9lg6dgjgfzr386jaxj5rx9ncg6qj4nuw9zy8zdnqpcf50y2qy63662yejarjk4njnurvlukyaxqsy22mkgsjujzl5s98rr026rsc36u7jtj3qu9fh99z5lvjmyqk9sffydfd5jt5gjx4y6l5z4vg6385ae0nkmmtnlh87tq8jezct828e3ce8ufvyu2wpuqrp4xzdacx4j09mx2g0f48yalrjd7zu0x6gmq88grnfm6wax8cl0evzrry9392uj9rgfmsxnf4swcddfgedjw299y7eh4v8932qa052jh7uc0hvpk5k0petmzqn77hjg8gaycxmr9uv690m5mver3x6c3y9gp326glheqemwhedrva2gwh2cls4y295l4z8x2p0ef9dqjx4yarjsrnv7cc5has9urnfxycqyd4u5q0wmqrr6rcl8d8srll92gfgxqlz6txac3vuqvx9jnh9mme5pt3dmu5axnnpxkwdcsgys8ksrgqg9n4ymjx96sq55kt9rl3vtt72dqzckkwpjrup4nxfvynh48rzz4fxm62ml0uy5a0em532v4vr9hzvw3jh9vhv3u7922d59r5tjyhhtje0fuxv6gd9fjd5cptycnyr8c4pxk65p42s2sl2gc60l43kyljqgsj8x602szvqruym0k5f3ds4pc8yj73z7g4m5ywllryefycjvl5kulrjppde6qq6uh45zppw0066jlw3esqa9q5q4t3txw9x4hk735hzzuxutc47w4hmexdrshkpfa3sqxpe9rn62mhcqe9r6zxfljkgvhvzpggrr3qlvusjrkz2cjmsfph6uy2v46dfzzv8mdcuscl4n5uc2nuzzhztqxjrd2q2hhk8rsmeeufw9epj8a3vfvfgxxue90j44jnwv9jx5q3rh06jrfj6u5rhct5ngvgqqarq0a5y34u297h9xfl64qymrvqc38rgxedqznlcyhr7j49a35ffyev48wzqygg86y54jqs9e9gxztckvwejurueg5952c2yc02epn3zsde7acyf34w4ltk3m0dj05j53xgfare44s0dc5z4cfc9jpuqapq348hgmcu406k6kdzp7jpx003xcmpgjee5ap55t5x4rr2as3q57zk4syx4mnk6z9vlhn2vwvhrqhsevserxxj45wwzp8c0qs60zjqxaxp4vf3pn8ch60c4pnhekwdkkv3ap4hrh3qp7sw54dcu464ajeky0vhntcppdqu5lykk33ykt3h5jc9ehrx7lnm969mx6m86cqzxcfr2u52zkgl0pztcq305ju6h0te3jw8frm238d4c2u3vy3ttq3j3frkz3hystugvsen0cur5qn59ty2fvx6nzjfagw8vjr5aqckttr0f0gxvp852gwys92qdrjqun52yk7uftcyldh5fryvzvz2t8z45k92qzn2smh50r2yylcf7l607xjep65407exs0yaa56hqn79v9ypam0ggsj67ce959we7yupahzk5nh57evdsy2sve7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T19:45:53Z"
  mac: ENC[AES256_GCM,data:sy6jx7gGIdgzniN39+HuGEigUkMe4tq9Ji6rw4NUK/bt+3Nrhu5v/rTaFpjzgMcbEvIFkZ9fF8Om9UoItrM3B/JKLFUTuLasft6YRlnO5Q99ku2k8TcDRs4P/MzzmFxNcJ9RzjXe6PgsfQfDgPlfwuiroP4LfJpBBGrmhADWSFQ=,iv:djyNeOPAKggy+wTLb1NN5aeqp0HMI3CeyvGCnBtDGQI=,tag:v91Sy5RoAo7Wb/jcJ+WU8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
